import { useEffect, useRef, useState } from "react";
import z from "zod";
import { MODEL, streamArticleForTopic, streamAsciiArtForTopic } from "./ai";

const FALLBACK_ARTICLE =
  "Mono is a word element and standalone term with several related meanings centered on the idea of “one” or “single.” It comes from the Greek word monos, meaning “alone” or “single,” and appears in many English words such as monologue, monochrome, and monorail. ";

const FALLBACK_ASCII_ART = `┌─────────────────────────────┐\n│█┌─────────────────────────┐█│\n│█│▓┌─────────────────────┐▓│█│\n│█│▓│▒┌─────────────────┐▒│▓│█│\n│█│▓│▒│░┌─────────────┐░│▒│▓│█│\n│█│▓│▒│░│ ┌─────────┐ │░│▒│▓│█│\n│█│▓│▒│░│ │ ┌─────┐ │ │░│▒│▓│█│\n│█│▓│▒│░│ │ │ ┌─■ │ │ │░│▒│▓│█│\n│█│▓│▒│░│ │ │ └───┘ │ │░│▒│▓│█│\n│█│▓│▒│░│ │ └───────┘ │░│▒│▓│█│\n│█│▓│▒│░│ └───────────┘░│▒│▓│█│\n│█│▓│▒│░└───────────────┘▒│▓│█│\n│█│▓│▒└───────────────────┘▓│█│\n│█│▓└───────────────────────┘█│\n■█└───────────────────────────┘`;

const drawBox = (str: string) => {
  const lines = str.split(/\r?\n/);
  const maxWidth = lines.reduce(
    (width, line) => Math.max(width, line.length),
    0,
  );
  const horizontal = "-".repeat(maxWidth + 2);
  const top = `+${horizontal}+`;
  const bottom = top;
  const middle = lines.map((line) => `| ${line.padEnd(maxWidth, " ")} |`);

  return [top, ...middle, bottom].join("\n");
};

export default function App() {
  const [article, setArticle] = useState(FALLBACK_ARTICLE);
  const [topic, setTopic] = useState("mono");
  const [asciiArt, setAsciiArt] = useState(FALLBACK_ASCII_ART);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const latestRequestId = useRef(0);
  const isMounted = useRef(true);

  useEffect(() => {
    return () => {
      isMounted.current = false;
    };
  }, []);

  const onSubmit = async (submission: string) => {
    if (process.env.TESTING) {
      setTopic(submission);
      setArticle(FALLBACK_ARTICLE);
      setAsciiArt(FALLBACK_ASCII_ART);
      return;
    }
    setIsLoading(true);

    const Submission = z
      .string()
      .trim()
      .regex(/^[a-zA-Z0-9 _-]*$/)
      .min(1, "Please enter a topic to search for.")
      .max(40, "Topic must be 40 characters or less.");
    const parsedSubmission = Submission.parse(submission);

    const requestId = ++latestRequestId.current;
    setError(null);
    setArticle("");
    setTopic(parsedSubmission);
    setAsciiArt("");

    const consumeAsciiArtStream = async () => {
      const result = await streamAsciiArtForTopic(parsedSubmission);
      if (!isMounted.current || requestId !== latestRequestId.current) {
        return;
      }
      setAsciiArt(result);
    };

    const consumeArticleStream = async () => {
      for await (const delta of streamArticleForTopic(parsedSubmission)) {
        if (!isMounted.current || requestId !== latestRequestId.current) {
          break;
        }
        setArticle((prev) => prev + delta);
      }
    };

    try {
      await Promise.all([consumeAsciiArtStream(), consumeArticleStream()]);
    } catch (error) {
      if (!isMounted.current || requestId !== latestRequestId.current) {
        return;
      }
      setError(
        error instanceof Error ? error.message : "Failed to generate article.",
      );
      setArticle(FALLBACK_ARTICLE);
    } finally {
      if (isMounted.current && requestId === latestRequestId.current) {
        setIsLoading(false);
      }
    }
  };

  return (
    <box
      width="100%"
      height="100%"
      paddingX={2}
      paddingTop={1}
      backgroundColor="#FFFFFF"
      border
      borderColor="#888888"
      bottomTitle={` Made by Luca Wang · Generated by ${MODEL.modelId} `}
      justifyContent="center"
      alignItems="center"
      flexGrow={1}
    >
      <box flexDirection="column" gap={2} flexGrow={1}>
        <box flexDirection="row" justifyContent="space-between">
          <box flexGrow={1}>
            <input
              value={input}
              placeholder="Start typing to search"
              textColor="#000000"
              onKeyDown={(key) => {
                if (key.name === "escape") {
                  setInput("");
                }
              }}
              onChange={setInput}
              onSubmit={(submission) => {
                if (typeof submission === "string") {
                  void onSubmit(submission);
                }
              }}
              cursorColor="#888888"
              showCursor
              focused
            />
          </box>
          <text selectable={false} fg="#000000">
            Random
          </text>
        </box>

        <box
          width="100%"
          flexDirection="row"
          gap={3}
          alignItems="flex-start"
          justifyContent="center"
        >
          <box flexShrink={0}>
            <text fg="#888888">
              {isLoading ? drawBox("Loading...") : drawBox(asciiArt)}
            </text>
          </box>

          <box flexGrow={1} flexShrink={1} minWidth="30%" maxWidth="50%">
            <box
              flexDirection="column"
              alignItems="flex-start"
              marginBottom={2}
              flexGrow={1}
              flexShrink={1}
            >
              <ascii-font
                text={topic}
                font="block"
                color="#000000"
                flexShrink={1}
              />
            </box>
            {isLoading ? <text fg="#888888">Generating...</text> : null}
            {error ? <text fg="#FF0000">Error: {error}</text> : null}
            <text selectionBg="#888888" selectable fg="#000000" flexShrink={1}>
              {article}
            </text>
          </box>
        </box>
      </box>
    </box>
  );
}
