import { ConsolePosition, createCliRenderer } from "@opentui/core";
import { createRoot } from "@opentui/react";
import { useState } from "react";

const FALLBACK_ARTICLE =
  "Mono is a word element and standalone term with several related meanings centered on the idea of “one” or “single.” It comes from the Greek word monos, meaning “alone” or “single,” and appears in many English words such as monologue, monochrome, and monorail. ";

const drawBox = (topic: string) => {
  const displayableTopic =
    topic.length > 20 ? `${topic.substring(0, 17)}...` : topic;
  const paddedTopic = ` ${displayableTopic} `;
  const topBorder = `┌${"─".repeat(paddedTopic.length)}┐`;
  const middle = `│${paddedTopic}│`;
  const bottomBorder = `└${"─".repeat(paddedTopic.length)}┘`;
  return `${topBorder}\n${middle}\n${bottomBorder}`;
};

function App() {
  const [article] = useState(FALLBACK_ARTICLE);
  const [searchInput, setSearchInput] = useState("");

  return (
    <box
      flexDirection="column"
      width="100%"
      height="100%"
      paddingX={2}
      paddingTop={1}
      paddingBottom={1}
      backgroundColor="#FFFFFF"
    >
      <box
        flexGrow={1}
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
        width="100%"
      >
        <box
          width="100%"
          maxWidth={100}
          flexDirection="row"
          alignItems="baseline"
          gap={2}
          marginBottom={2}
        >
          <box flexGrow={1}>
            <input
              value={searchInput}
              placeholder="start typing to search"
              textColor="#000000"
              onKeyDown={(key) => {
                if (key.name === "escape") {
                  setSearchInput("");
                }
              }}
              onSubmit={(submitEvent) => setSearchInput(submitEvent as string)}
              cursorColor="#888888"
              showCursor
              focused
            />
          </box>
          <text fg="#000000">Random</text>
        </box>

        <box
          width="100%"
          maxWidth={72}
          flexDirection="column"
          alignItems="center"
          marginBottom={2}
        >
          <ascii-font text="MONO" font="block" color="#000000" />
        </box>

        <box width="100%" maxWidth={72} flexDirection="column" gap={1}>
          <box marginTop={1}>
            <text fg="#888888">{drawBox("mono")}</text>
          </box>
          <text fg="#000000">{article}</text>
        </box>
      </box>

      <box width="100%" justifyContent="center" paddingTop={1}>
        <text fg="#888888">
          Mono by Luca Wang · Generated by {"{UNKNOWN_MODEL}"}
        </text>
      </box>
    </box>
  );
}

const renderer = await createCliRenderer({
  openConsoleOnError: true,
  backgroundColor: "#888888",
  consoleOptions: {
    position: ConsolePosition.BOTTOM, // Position on screen
    sizePercent: 30, // Size as percentage of terminal
    colorInfo: "#00FFFF", // Color for console.info
    colorWarn: "#FFFF00", // Color for console.warn
    colorError: "#FF0000", // Color for console.error
    startInDebugMode: false, // Show file/line info in logs
  },
});

renderer.keyInput.on("keypress", (key) => {
  // Toggle with backtick key
  if (key.name === "`") {
    renderer.console.toggle();
  }

  // Or with a modifier
  if (key.ctrl && key.name === "l") {
    renderer.console.toggle();
  }
});

createRoot(renderer).render(<App />);
