import { ConsolePosition, createCliRenderer } from "@opentui/core";
import { createRoot } from "@opentui/react";
import { useEffect, useRef, useState } from "react";
import { MODEL, streamArticleForTopic } from "./ai";

const FALLBACK_ARTICLE =
  "Mono is a word element and standalone term with several related meanings centered on the idea of “one” or “single.” It comes from the Greek word monos, meaning “alone” or “single,” and appears in many English words such as monologue, monochrome, and monorail. ";

const drawBox = (topic: string) => {
  const displayableTopic =
    topic.length > 20 ? `${topic.substring(0, 17)}...` : topic;
  const paddedTopic = ` ${displayableTopic} `;
  const topBorder = `┌${"─".repeat(paddedTopic.length)}┐`;
  const middle = `│${paddedTopic}│`;
  const bottomBorder = `└${"─".repeat(paddedTopic.length)}┘`;
  return `${topBorder}\n${middle}\n${bottomBorder}`;
};

function App() {
  const [article, setArticle] = useState(FALLBACK_ARTICLE);
  const [topic, setTopic] = useState("mono");
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const latestRequestId = useRef(0);
  const isMounted = useRef(true);

  useEffect(() => {
    return () => {
      isMounted.current = false;
    };
  }, []);

  const onSubmit = async (submission: string) => {
    const normalizedSubmission = submission.trim();
    if (!normalizedSubmission) {
      return;
    }

    const requestId = ++latestRequestId.current;
    setError(null);
    setIsLoading(true);
    setArticle("");
    setTopic(normalizedSubmission);

    try {
      const textStream = await streamArticleForTopic(normalizedSubmission);
      for await (const delta of textStream) {
        if (!isMounted.current || requestId !== latestRequestId.current) {
          break;
        }
        setArticle((prev) => prev + delta);
      }
    } catch (error) {
      if (!isMounted.current || requestId !== latestRequestId.current) {
        return;
      }
      setError(
        error instanceof Error ? error.message : "Failed to generate article.",
      );
      setArticle(FALLBACK_ARTICLE);
    } finally {
      if (isMounted.current && requestId === latestRequestId.current) {
        setIsLoading(false);
      }
    }
  };

  return (
    <box
      flexDirection="column"
      width="100%"
      height="100%"
      paddingX={2}
      paddingTop={1}
      paddingBottom={1}
      backgroundColor="#FFFFFF"
    >
      <box
        flexGrow={1}
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
        width="100%"
      >
        <box
          width="100%"
          maxWidth={100}
          flexDirection="row"
          alignItems="baseline"
          gap={2}
          marginBottom={2}
        >
          <box flexGrow={1}>
            <input
              value={input}
              placeholder="Start typing to search"
              textColor="#000000"
              onKeyDown={(key) => {
                if (key.name === "escape") {
                  setInput("");
                }
              }}
              onChange={setInput}
              onSubmit={(submission) => {
                if (typeof submission === "string") {
                  void onSubmit(submission);
                }
              }}
              cursorColor="#888888"
              showCursor
              focused
            />
          </box>
          <text selectable={false} fg="#000000">
            Random
          </text>
        </box>

        <box
          width="100%"
          maxWidth={72}
          flexDirection="column"
          alignItems="center"
          marginBottom={2}
        >
          <ascii-font text="MONO" font="block" color="#000000" />
        </box>

        <box
          width="100%"
          maxWidth={72}
          flexDirection="column"
          overflow="scroll"
        >
          <box marginTop={1} marginBottom={2}>
            <text fg="#888888">{drawBox(topic)}</text>
          </box>
          {isLoading ? <text fg="#888888">Generating...</text> : null}
          {error ? <text fg="#FF0000">Error: {error}</text> : null}
          <text selectionBg="#888888" selectable fg="#000000">
            {article}
          </text>
        </box>
      </box>

      <box width="100%" justifyContent="center" paddingTop={1}>
        <text fg="#888888">
          Made by Luca Wang · Generated by {MODEL.modelId}
        </text>
      </box>
    </box>
  );
}

const renderer = await createCliRenderer({
  openConsoleOnError: true,
  backgroundColor: "#888888",
  consoleOptions: {
    position: ConsolePosition.BOTTOM, // Position on screen
    sizePercent: 30, // Size as percentage of terminal
    colorInfo: "#00FFFF", // Color for console.info
    colorWarn: "#FFFF00", // Color for console.warn
    colorError: "#FF0000", // Color for console.error
    startInDebugMode: false, // Show file/line info in logs
  },
});

renderer.keyInput.on("keypress", (key) => {
  // Toggle with backtick key
  if (key.name === "`") {
    renderer.console.toggle();
  }

  // Or with a modifier
  if (key.ctrl && key.name === "l") {
    renderer.console.toggle();
  }
});

createRoot(renderer).render(<App />);
